---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/valluri:dbserver
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/valluri:appserver
   ports:
     - "1235:8080"
   depends_on:
     - "devopsdb"
